FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/backend/package*.json ./packages/backend/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w backend

COPY ./packages/ ./backend/
COPY ./packages/ ./shared/

RUN npm run build -w packages/backend

EXPOSE 3000

CMD ["node", "backend/dist/app.js"]